name = "smart-assistant"
pages_build_output_dir = "dist"
compatibility_date = "2024-01-01"

[triggers]
crons = ["* * * * *"] # Every minute

[[kv_namespaces]]
binding = "NOTIFIED_CACHE"
id = "NOTIFIED_CACHE_ID_PLACEHOLDER" # User needs to create this or it will be auto-created on deployment
